#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FileList.Resource", IsApplication=false)]

namespace FileList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int showCurrentDir = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int showHiddenFiles = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int file = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int folder = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public static int FileList_CurrentDir = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int FileList_ListView = 2131034120;
			
			// aapt resource value: 0x7f050006
			public static int FileList_MainLayout = 2131034118;
			
			// aapt resource value: 0x7f050000
			public static int file_picker_image = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int file_picker_info_attribute = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int file_picker_info_datetime = 2131034117;
			
			// aapt resource value: 0x7f050003
			public static int file_picker_info_size = 2131034115;
			
			// aapt resource value: 0x7f050001
			public static int file_picker_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int infoGrid = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int file_picker_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int FileListViewWithDirName = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int Elements = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int Folder = 2130968577;
			
			// aapt resource value: 0x7f040003
			public static int ToastDirectoryContentsError = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FileListView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int FileListView_showCurrentDir = 0;
			
			// aapt resource value: 1
			public static int FileListView_showHiddenFiles = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
