#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProvaFileList.Resource", IsApplication=true)]

namespace ProvaFileList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FileList.Resource.Attribute.showCurrentDir = global::ProvaFileList.Resource.Attribute.showCurrentDir;
			global::FileList.Resource.Attribute.showHiddenFiles = global::ProvaFileList.Resource.Attribute.showHiddenFiles;
			global::FileList.Resource.Drawable.file = global::ProvaFileList.Resource.Drawable.file;
			global::FileList.Resource.Drawable.folder = global::ProvaFileList.Resource.Drawable.folder;
			global::FileList.Resource.Id.FileList_CurrentDir = global::ProvaFileList.Resource.Id.FileList_CurrentDir;
			global::FileList.Resource.Id.FileList_ListView = global::ProvaFileList.Resource.Id.FileList_ListView;
			global::FileList.Resource.Id.FileList_MainLayout = global::ProvaFileList.Resource.Id.FileList_MainLayout;
			global::FileList.Resource.Id.file_picker_image = global::ProvaFileList.Resource.Id.file_picker_image;
			global::FileList.Resource.Id.file_picker_info_attribute = global::ProvaFileList.Resource.Id.file_picker_info_attribute;
			global::FileList.Resource.Id.file_picker_info_datetime = global::ProvaFileList.Resource.Id.file_picker_info_datetime;
			global::FileList.Resource.Id.file_picker_info_size = global::ProvaFileList.Resource.Id.file_picker_info_size;
			global::FileList.Resource.Id.file_picker_text = global::ProvaFileList.Resource.Id.file_picker_text;
			global::FileList.Resource.Id.infoGrid = global::ProvaFileList.Resource.Id.infoGrid;
			global::FileList.Resource.Layout.file_picker_list_item = global::ProvaFileList.Resource.Layout.file_picker_list_item;
			global::FileList.Resource.Layout.FileListViewWithDirName = global::ProvaFileList.Resource.Layout.FileListViewWithDirName;
			global::FileList.Resource.String.ApplicationName = global::ProvaFileList.Resource.String.ApplicationName;
			global::FileList.Resource.String.Elements = global::ProvaFileList.Resource.String.Elements;
			global::FileList.Resource.String.Folder = global::ProvaFileList.Resource.String.Folder;
			global::FileList.Resource.String.ToastDirectoryContentsError = global::ProvaFileList.Resource.String.ToastDirectoryContentsError;
			global::FileList.Resource.Styleable.FileListView = global::ProvaFileList.Resource.Styleable.FileListView;
			global::FileList.Resource.Styleable.FileListView_showCurrentDir = global::ProvaFileList.Resource.Styleable.FileListView_showCurrentDir;
			global::FileList.Resource.Styleable.FileListView_showHiddenFiles = global::ProvaFileList.Resource.Styleable.FileListView_showHiddenFiles;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int showCurrentDir = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int showHiddenFiles = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int file = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int folder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int FileList_CurrentDir = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int FileList_ListView = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int FileList_MainLayout = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int MainLayout = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int checkBoxShowDirectory = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int fileListView = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int file_picker_image = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int file_picker_info_attribute = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int file_picker_info_datetime = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int file_picker_info_size = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int file_picker_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int infoGrid = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int file_picker_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FileListViewWithDirName = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Elements = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Folder = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ToastDirectoryContentsError = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FileListView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int FileListView_showCurrentDir = 0;
			
			// aapt resource value: 1
			public const int FileListView_showHiddenFiles = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
